#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
#
# Requirements:
#   Accept 4 paramenters
#       - The path to the file to be transferred
#       - The IP of the server we want to transfer the file to
#       - The username scp connects with
#       - The path to the SSH private key that scp uses
#   Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY 
#       if less than 3 parameters passed
#   scp must transfer the file to the user home directory ~/
#   Strict host key checking must be disabled when using scp

#echo "$#"
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
