#!/usr/bin/env bash
# Configure your Nginx server to have a
#   custom 404 page that contains the string Ceci n'est pas une page.
#
#   Requirements:
#
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404
# so that it configures a brand new Ubuntu machine to the requirements asked in this task

# Update Ubuntu pakage list
sudo apt-get update -y

# Upgrade Ubuntu packages
sudo apt-get upgrade -y

# Install NGINX
sudo apt-get install nginx -y

# Install Firewall
sudo apt-get install ufw -y

# Enable NGINX http profile
sudo ufw allow 'Nginx http'

# Reasign ownership of the web directories to normal user account
sudo chown -R "$USER":"$USER" /var/www/

# Create 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure NGINX to respond to 404 error
err="server_name _; \n\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sed -i "s#server_name _;#$err#" /etc/nginx/sites-available/default 

# Configure NGINX to respond to /redirect_me
conf="server_name _; \n\n\tlocation /redirect_me { \n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t }"

sed -i "s#server_name _;#$conf#" /etc/nginx/sites-available/default


# Start NGINX server
sudo service nginx start
# Reload NGINX
sudo service nginx reload
