#!/usr/bin/env bash
# Script that configures a brand new Ubuntu machine to the requirements below:
# REQUIREMENTS:
#   Configure Nginx so that its HTTP response contains a custom header 
#       (on web-01 and web-02)
#   The name of the custom HTTP header must be X-Served-By

# Helper function that installs a package
install_software() {
    local software_name="$1"
    #   Check if nginx is installed
    if command -v "$software_name" &> /dev/null; then
        echo "$software_name is already installed on this machine"
    else
        echo "Installing $software_name"
        #   Update Ubuntu package list
        sudo apt-get update
        #   Install software
        sudo apt-get install -y "$software_name"
        echo "$software_name has been installed"
    fi
}

create_path () {
    if [[ ! -d "$1" ]]; then
        mkdir -p "$1"
        echo "Directory $1 created successfully"
    else
        echo "Direcroty $1 already exists"
    fi
}

# Install nginx if not installed
install_software "nginx"

# Install Firewall if not installed
install_software "ufw" 
# Allow http traffic to nginx
sudo ufw allow 'Nginx http'

# Reassign ownership of the web directories to normal user account
sudo chown -R "$USER":"$USER" /var/www/

# Change the index page content
echo "Hello World!" | sudo tee /var/www/html/index.html &> /dev/null

# Configure nginx to respond to /redirect_me
conf="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s#server_name _;#$conf#" /etc/nginx/sites-available/default

# Create custom server 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Configure nginx to respond to 404 error
err="server_name _;\n\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s#server_name _;#$err#" /etc/nginx/sites-available/default

# Add custom response header
hdr="http {\n\n\tadd_header X-Served-By $(hostname);\n\n"

sudo sed -i "s#http {#$hdr#" /etc/nginx/nginx.conf

# Test nginx config files for errors
sudo nginx -t
# Reload nginx
sudo service nginx reload
