#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
min=1

while [ $hour -le 13 ]; do
	if [ $min -eq 60 ] || [ $hour -eq 0 ]; then
		if [ $hour -ne 13 ]; then
			echo "Hour: $hour"
		fi
		((min=1))
		if [ $hour -ne 13 ]; then
			echo "$min"
		fi
		((hour++))
	else
		echo "$min"
	fi

	#if [ $min -eq 60 ]; then
	#fi
	((min++))
done
