#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

list=$(ls)
for name in $list; do
	echo "$name" | cut -d "-" -f2
done
